# Generated by Django 5.2.1 on 2025-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Disk_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_MIC_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
