# Generated by Django 5.2.1 on 2025-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0002_alter_final_antibioticentry_ab_disk_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Abx_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_AccessionNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
