# Generated by Django 5.2.1 on 2025-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_breakpointstable_retest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TATexclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Excluded', models.DateField(blank=True, null=True)),
                ('Exclusion_Details', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Date_Excluded',
            },
        ),
    ]
