# Generated by Django 5.2.1 on 2025-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tatexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpointstable',
            name='Org_Grp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
