# Generated by Django 5.2.1 on 2025-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_breakpointstable_org_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whonet_Org_Code', models.CharField(max_length=20, unique=True)),
                ('Replaced_by', models.CharField(blank=True, max_length=20, null=True)),
                ('Organism', models.CharField(max_length=255)),
                ('Organism_Type', models.CharField(blank=True, max_length=5, null=True)),
                ('Subkingdom_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Family_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('Genus_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Genus_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('Species_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Serovar_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('Phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Order', models.CharField(blank=True, max_length=100, null=True)),
                ('Family', models.CharField(blank=True, max_length=100, null=True)),
                ('Genus', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
