# Generated by Django 5.2.1 on 2025-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_organism_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_uploadOrg', models.FileField(blank=True, null=True, upload_to='uploads/organism/')),
            ],
            options={
                'db_table': 'Organism_upload',
            },
        ),
    ]
