# Generated by Django 5.2.1 on 2025-11-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_organism_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism_list',
            name='Subkingdom_Code',
        ),
    ]
