# Generated by Django 5.2.1 on 2025-11-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_organism_list_subkingdom_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referred_data',
            old_name='OrganismCode',
            new_name='Site_OrgName',
        ),
    ]
