# Generated by Django 5.2.1 on 2025-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_organismcode_referred_data_site_orgname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='Site_Org',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='ars_OrgCode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
